services:
  - type: worker
    name: ore-refined-miner
    env: rust
    buildCommand: |
      npm install
      cargo build --release
    startCommand: ./scripts/start.sh
    envVars:
      - key: RPC_URL
        value: https://api.mainnet-beta.solana.com
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: PER_ROUND_DEPLOY_AMOUNT
        value: 0.0001
      - key: REMAINING_SLOTS
        value: 15
      - key: ORE_REFINED_RATE
        value: 1.3
      - key: PUBLIC_KEY
        value: 8BEuH1JdD5wTVJfBh2y6htgjiBUyuZ1keDLdi1FpU39b

